### ISSUE TITLE
Support for executing commands on different ways missing

### ISSUE THREAD

**Issue by kikelkik** [AngrySoundTech/CouponCodes3#25]
Hey!
I don't want to let players type in the redeem command in chat themselves (They shouldn't know how coupons are called, because I'm using them for item based eastereggs). 
But unfortunately, it is neither possible to let players execute /coupon redeem <...> by a commandblock nor by commandsigns e.g. ServerSigns. 
The answer of couponcodes is just "/coupon" when I try it. Creating alias commands in commands.yml (such as /redeem for /coupon redeem) works well - but only by typing it into chat by myself.

Whould be great If you implemented this opportunity using couponcodes more effective! 

Please let me know.
kikelkik

**Comment by AngrySoundTech** [comment]
As the redeem command is meant to be run by a player, it is unable to be run by a command block or sign.

The only way to do this would be to use another plugin that mocks the player running the command, which is by design not part of CouponCodes

**Comment by kikelkik** [comment]
Sorry, my explanation might have been a bit confusing.
I do not want to mock the player running the command. Players still got permission for that command. What I miss is the ability for letting players execute the command by another plugin/commandblock.

**Comment by kikelkik** [comment]
Do you know what I mean? Would you like to answer here or shall I open a new ticket for my issue?

**Comment by AngrySoundTech** [comment]
I understand what you mean, but command blocks don't have the player run the command. It is always run as the console. The redeem command should be run by a player.

**Comment by kikelkik** [comment]
Actually the /execute command by minecraft runs the command as if it was the player. E.g. you can do "/execute @p ~ ~ ~ msg angrysoundtech hi" - In result, the sender is not the console but a player near to the cmd-block.
In detail, I tried /execute @p ~ ~ ~ coupon redeem <coupon>, /execute @p ~ ~ ~ couponcodes:coupon redeem <coupon> and /execute @p ~ ~ ~ redeem <coupon> (created an alias "redeem" for "coupon redeem). I put all these commands in a command block which gave me just a "/coupon" in Chat.

**Comment by AngrySoundTech** [comment]
The /execute command only works with vanilla commands.

If you are using essentials, I would recommend trying the /sudo command. For example:
<code>sudo @p coupon redeem \<coupon name></code>

**Comment by kikelkik** [comment]
I did already test it with /sudo - same result: it outputs me a "/coupon" in chat.
Usin' serversigns and tried /svs add <player> coupon redeem as well.
It works with any other plugin except couponcodes
